services:
  - type: web
    name: telegram-view-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: NORMAL_BOT_TOKEN
        sync: false
      - key: PRO_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
    plan: free
    autoDeploy: true
